### ISSUE TITLE
TestDev Set

### ISSUE THREAD

**Issue by maximedb** [doc2dial/sharedtask-dialdoc2021#4]
Hi,

The turns in `doc2dial_dial_testdev.json` available on eval.ai do not contain any dialogue act or references, whereas the validation set does. Is this to be expected?

Thank you!

Maxime.

**Comment by songfeng** [comment]
Hi,

Yes, there are no dialogue acts or grounding references in the test-dev or final test set. If the generation (subtask2) uses dialogue act or grounding references, the model needs to predict those.

Thanks!

**Comment by maximedb** [comment]
Ok, that was not clear to me. Thank you!
