### ISSUE TITLE
Keys for dialogues

### ISSUE THREAD

**Issue by ddrous** [doc2dial/sharedtask-dialdoc2021#9]
This [README](https://github.com/doc2dial/sharedtask-dialdoc2021/blob/master/data/doc2dial/DATA_README.md) says the dialogue data are indexed by `domain` and `doc_id`. Is this a typo and you meant to say `domain` and `dial_id` instead ?

**Comment by songfeng** [comment]
Many thanks for the comment!

Here by "indexed by `domain` and `doc_id`", we meant that we group the dialogue by some kind of hierarchy. Specifically, one can get all dialogues under a given `domain` or all dialogues under a given `domain` + `doc_id`.

I have made some minor changes in README to clarify that.

**Comment by ddrous** [comment]
Thanks for your answer, I think I get what you mean 🙂
